### ISSUE TITLE
Peak picking in zone

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-processing#18]
When we draw a zone there should be a way to find the peak in the zone and not simply calculate the middle in both dimensions.

We should take care of cosy DQF when there are many peaks in fact and some of them may be negative.

**Comment by jobo322** [comment]
The method take in account the negative peaks. Also we export the peaks for each zone. Could you explain a little bit deeper what is the behavior that you expect?

**Comment by jobo322** [comment]
It is apparently done.
