### ISSUE TITLE
Add a method for peak shape analysis

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-processing#183]
We need a method that is able to optimize a peak and extract the shape of it.

See: https://github.com/cheminfo/nmrium/issues/1668

I guess we need the following options (not sure if all of them could be guessed)
- from / to
- peak that contains x,y,shape

**Comment by lpatiny** [comment]
This problem is probably related to https://github.com/mljs/spectra-fitting/issues/92 and @jobo322  you could go throw all the issues that are still open on https://github.com/mljs/spectra-fitting/issues

**Comment by jobo322** [comment]
@lpatiny there is a PR with it done

mainly it is a wrapper of ml-gsd/optimizePeaks 

https://github.com/cheminfo/nmr-processing/pull/188
