### ISSUE TITLE
Add unique ID

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-processing#205]
In order to facilitate linking peaks, ranges, signals the method that create those entities should directly add an `id` (we will always use id as property name).

This means automatic peak picking, signal picking, etc.

This will also be the case in nmr-load-save to identify a spectrum for example.

@jobo322 Could you add this id using as library @lukeed/uuid ?

**Comment by jobo322** [comment]
@lpatiny what do you think about adding this feature in ml-gsd and ml-spectra-fitting too? Those two packages are used for peak-related functions in nmr-processing and it returns a new clean structure so the `id` property is deleted if the peak passes for an optimization step.

**Comment by lpatiny** [comment]
Our packages could return id if it exists indeed. In typescript there is probably a way to tell that if it is defined in the input function it is returned so that we don't need to check if it is undefined.

**Comment by lpatiny** [comment]
Would be something like that I guess: https://stackoverflow.com/questions/67655629/make-typescript-return-type-depend-on-whether-optional-property-is-present

**Comment by targos** [comment]
> Would be something like that I guess: https://stackoverflow.com/questions/67655629/make-typescript-return-type-depend-on-whether-optional-property-is-present

That's not how I would do it. Please ping me on the pull request where you implement id handling
