### ISSUE TITLE
Optimize signals ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-processing#211]
This is related to https://github.com/mljs/peak-shape-generator/issues/73 and it is probably a better place to do it here.

We could add a method that allows to fit signals by allowing optimization of the signal parameters.

This would allow to optimize 2 overlapping signals while obtaining an accurate result for the integration. This would also be very useful in the metabolomics field if we can optimize many spectra at once.

**Comment by jobo322** [comment]
@lpatiny, it would be a good feature, do you mean optimize signals with the structure of [NMRSignal1D](https://github.com/cheminfo/nmr-processing/blob/main/src/signals/NMRSignal1D.ts)?

**Comment by lpatiny** [comment]
Yes. But I guess that all the peaks should be there and have the same shape. They are also expected to have the same width in order to reduce the number of parameters.

We also need to define the range of value to explore. I guess for coupling it should rather be a small range. Just try to find an example with 2 overlapping doublets to try to define a function to make the optimization and we can rediscuss about it.
