### ISSUE TITLE
Prediction error: cannot rescale a constant array

### ISSUE THREAD

**Issue by targos** [cheminfo/nmr-processing#217]
With https://www.nmrium.org/predict?smiles=COCOCCCCC

**Comment by jobo322** [comment]
seems it is working, could you check if the from-to that you are using? with the default values it works well

![Image](https://user-images.githubusercontent.com/12143935/192543132-55a84c71-163e-4f29-bbe8-a482999fd65c.png)

**Comment by jobo322** [comment]
This error usually appears when all the signals of the prediction are outside of the from-to passed. We could check it an throw before it try to rescale. what do you think?

**Comment by targos** [comment]
I don't pass from-to, it must be using the default values from this package

**Comment by targos** [comment]
But it seems fixed indeed.
