### ISSUE TITLE
generate FID

### ISSUE THREAD

**Issue by jwist** [cheminfo/nmr-processing#219]
N = size of array
time = array(0, T, length.out = N)

s_t = exp(%i*2*%pi*omega.*time) .*exp(-R.*time);

T is time in second
R is relaxation time in s-1
omega is frequency in Hz

**Comment by lpatiny** [comment]
<img width="1470" alt="Screenshot 2022-11-10 at 15 36 00" src="https://user-images.githubusercontent.com/1484241/201201575-8dcfc3eb-362a-4521-8793-46ee82dd60ae.png">
