### ISSUE TITLE
add FilterManager that can be used in nmrium

### ISSUE THREAD

**Issue by jobo322** [cheminfo/nmr-processing#236]
The idea is to have a filter Manager in nmr-processing that can be used in nmrium for processing

**Comment by lpatiny** [comment]
@jobo322 You should better describe the issue because I don't know what is the problem and how you plan to solve it.

An example of the code before / after would be great.

**Comment by jobo322** [comment]
in nmrium package we have, the filterManager that manage all the filter and update the `filters` list. So, the idea is to have a similar function in nmr-processing so we can use this function to apply a manual phase-correction outside of nmrium, @lpatiny  WDT?

**Comment by lpatiny** [comment]
Please could you propose a function name with the parameter and the return value ?

One important problem to take into account is that in .nmrium we need to know if it is a FID or not so we can not just return the x,y data.
