### ISSUE TITLE
Add more test in predictSpectra

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-processing#317]
You should check that the info is correct for ALL predicts because currently it is false

For carbon and proton it is ok: 

BTW should nucleus be an array in all the cases ????? I would say yes because once it is a string and once it is an array. Please check how we did it in NMRium.

```
     info: {
          nucleus: '1H',
          dimension: 1,
          isComplex: false,
          originFrequency: 400,
          baseFrequency: 400,
          pulseSequence: 'prediction',
          experiment: 'proton',
          isFt: true
        },

        info: {
          nucleus: '13C',
          dimension: 1,
          isComplex: false,
          originFrequency: 100.6015099440531,
          baseFrequency: 100.6015099440531,
          pulseSequence: 'prediction',
          experiment: 'carbon',
          isFt: true
        },
```

For HSQC HMBC COSY it is wrong. Frequencies are not defined.
```
      {
        data: { rr: [Object] },
        info: {
          nucleus: [Array],
          originFrequency: 'undefined,NaN',
          baseFrequency: 'undefined,NaN',
          pulseSequence: 'hsqc',
          experiment: '2d'
        },
        zones: { values: [Array] }
      },
      {
        data: { rr: [Object] },
        info: {
          nucleus: [Array],
          originFrequency: 'undefined,NaN',
          baseFrequency: 'undefined,NaN',
          pulseSequence: 'hmbc',
          experiment: '2d'
        },
        zones: { values: [Array] }
      },
      {
        data: { rr: [Object] },
        info: {
          nucleus: [Array],
          originFrequency: 'undefined,undefined',
          baseFrequency: 'undefined,undefined',
          pulseSequence: 'cosy',
          experiment: '2d'
        },
```

**Comment by lpatiny** [comment]
My main issue is that: https://www.nmrium.org/predict?smiles=CCCC

Predicts apparently all the spectra but they are not displayed:

![image](https://github.com/cheminfo/nmr-processing/assets/1484241/ca3a8552-0ade-4a61-9532-29b8005e8637)

**Comment by jobo322** [comment]
In the case of 1D nucleus is `string`. 
In the case of 2D nucleus is `string[]`.

The same molecule is well predicted in dev.nmrium.org, I will check what is wrong in predictSpectra

**Comment by jobo322** [comment]
is it possible that you are passing only options for proton and carbon prediction? At the moment we are predicting only the experiments with options, I mean:

```js
const { spectra } = predictSpectra(
   molecule, {
      prediction: {
         H: {},
         C: {}
     }
});
```
It will only predict proton and carbon spectra. we could add to `prediction` option and spectra property with: 
```js
{ 
  proton: boolean;
  carbon: boolean;
  ...
}
so, we could check this property before check the prediction options

**Comment by jobo322** [comment]
it is done by 79420b8b73f88bab4a37f262d8a0871ac03aecb2
