### ISSUE TITLE
signalsToXY fails with large system

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-processing#46]
I added a testcase that fails to break the spin system

**Comment by lpatiny** [comment]
The prediction of butane is completely wrong currently:

![image](https://user-images.githubusercontent.com/1484241/111742404-6963a580-8888-11eb-8041-99bf7ea80a09.png)

@jobo322 could you check why ?

**Comment by jobo322** [comment]
It was clarified some time ago.
