### ISSUE TITLE
Strange problem with google release action

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-processing#62]
@targos Could you help us on this ?

I don't think we did anything wrong but the release action is not working anymore.

https://github.com/cheminfo/nmr-processing/runs/2608600499?check_suite_focus=true

I tried to force the release to v1.4.0 but without success

**Comment by targos** [comment]
There is an incident with github actions, maybe related: https://www.githubstatus.com/incidents/m16jzl31gnqt
