### ISSUE TITLE
What is base ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-processing#8]
In peak picking to what corresponds 'base' in the result ?

https://github.com/cheminfo/nmr-processing/blob/1884900b54c4ff0074201f2e0bcf7951baa1b7eb/src/xy/__tests__/xyAutoPeaksPicking.test.js#L16-L25

I saw this line

https://github.com/mljs/global-spectral-deconvolution/blob/65ded7593df9cc8247a73b17cbbe5b224972370e/src/gsd.js#L234-L237

But can not find out what it is used for and if it should be present at all.

**Comment by jobo322** [comment]
I am almost sure that it corresponds to the noise level of the spectrum. It is is coming from the beginning of GSD package but currently I have not found a package that use it.
