### ISSUE TITLE
rangesToXY

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-processing#91]
I would like that we are able to `resurrect` publication strings like:

```
	1H-NMR (400 MHz, CDCl3) 5.96 (dd, J1 = 10.0 Hz, J2 = 5.4 Hz, 1 H), 5.71 (dd, J1 = 
	10.1 Hz, J2 = 1.1 Hz, 1 H), 5.14 (br. s, 1 H), 4.71 (dd, J1 = 11.1 Hz, J2 = 3.7 Hz, 1 H), 
	4.07 (sept., J = 6.2 Hz, 1 H), 2.41 (dd, J1 = 17.7 Hz, J2 = 11.2 Hz, 1 H), 2.23 (dd, J1 = 
	17.7 Hz, J2 = 4.1 Hz, 1 H), 1.29 (d, J = 6.2 Hz, 3 H), 1.19 (d, J = 6.1 Hz, 3 H), 1.00 (t, 
	J = 7.8 Hz, 9 H), 0.63 (q, J = 7.8 Hz, 6 H).`;
```

And I started to write the code that allows to resurrect the spectrum.  This code yields to an array of ranges and not an array of signals.

We have couple of subtleties here:

* the number of atoms is in `integration` and likely not in signals.atomIDs.length
* we have sometimes `multiplet` or `s br`

We would need a new method `rangesToXY` that could deal with all the kind of ranges array we generate. `resurrect()` is still a work in progress so we can definitely change his output format.

@jobo322 Could you start this code ? I think we can extract the signals but we will also need to extract the integration at the level of range.

We should also somehow simulate different shape of peaks. If we have a 's br' for example it could be 10 times larger than a normal peak while keeping the same integral. Also when we have 'm' we actually don't know the multiplicity of the peak and we should somehow simulate something. If we have a 'from / to' at the level of the range the stuff we simulate should have this width as well. I don't know if we should have a `square` signal with the same integration or a virtual multiplet by setting arbitrarily a complex multiplicity.  And if we go for a `square` signal I hope that https://github.com/mljs/peak-shape-generator can accommodate this kind of shape.

**Comment by jobo322** [comment]
It is done b04ab373c635811af6fca945fb9056be0aeac398
